channels:
- conda-forge
dependencies:
- python=3.8.5
- pip
- pip:
  - mlflow
  - cloudpickle==1.6.0
  - lightgbm==3.3.0
  - matplotlib==3.3.2
  - pandas==1.1.3
  - psutil==5.7.2
  - scikit-learn==0.0
  - typing-extensions==3.7.4.3
name: mlflow-env
